[package]
name = "zk-mahjong-circuits"
version = "0.1.0"
edition = "2021"

[dependencies]
zk-mahjong-core = { path = "../core" }
halo2_proofs.workspace = true
ff.workspace = true
smallvec.workspace = true